---
- name: Install Docker role from Ansible Galaxy
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install geerlingguy.docker role
      ansible.builtin.command:
        cmd: "ansible-galaxy install geerlingguy.docker -p ./roles"
      become: true

- name: Install Docker role to linux server
  hosts: linux_server
  become: yes
  tasks:
    - name: Include geerlingguy.docker role
      ansible.builtin.import_role:
        name: geerlingguy.docker
      become: true
