---
- name: Stop and Uninstall Apache Web Server
  hosts: linux_server
  become: yes

  tasks:
    - name: Stop Apache Service
      systemd:
        name: httpd
        state: stopped

    - name: Uninstall Apache Package
      package:
        name: httpd
        state: absent
