---
- name: Uninstall Apache Web Server
  hosts: linux_server
  roles:
    - geerlingguy.apache
      vars:
        apache_remove_default_vhost: true
        apache_remove_default_conf: true
        apache_remove_default_index: true
        apache_remove_default_ssl_cert: true
        apache_service_state: stopped
        apache_service_enabled: no
